### ISSUE TITLE
v1.0.2 is missing /lib folder

### ISSUE THREAD

**Issue by jacob-beltran** [archcorsair/react-isomorphic-scriptloader#3]
Hi the latest published version is broken. Seems to be missing the /lib folder. Pls help :)

**Comment by archcorsair** [comment]
🤦‍♂️  I'm so sorry, I got home late last night and forgot to compile it. Published *with* /lib folder this time.

**Comment by jacob-beltran** [comment]
Thanks so much!!
Also, quick tip, you can handle building automatically when you run npm publish by adding a prepublish script to your package.json.
https://docs.npmjs.com/misc/scripts#prepublish-and-prepare
